// Generated by create_ios_scaffold.py
import SwiftUI

struct ContentView: View {
    var body: some View {
        ZStack {
            LinearGradient(
                colors: [Color.black, Color(red: 0.08, green: 0.08, blue: 0.10)],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()

            VStack(spacing: 18) {
                Image(systemName: "music.note.list")
                    .font(.system(size: 64, weight: .semibold))
                    .foregroundStyle(.white)

                Text("Echo")
                    .font(.largeTitle.bold())
                    .foregroundStyle(.white)

                Text("iOS scaffold build")
                    .font(.headline)
                    .foregroundStyle(.white.opacity(0.85))

                Text("This target proves that CI can build an iOS app. The Android Kotlin/Compose/Media3 player code still needs a real iOS port before Echo playback features work on iPhone.")
                    .font(.callout)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(.white.opacity(0.72))
                    .padding(.horizontal, 28)
            }
            .padding()
        }
    }
}

#Preview {
    ContentView()
}
